### Home API
GET  http://localhost:3000/

### Muestra todo el contenido
GET  http://localhost:3000/contenidos

### Muestra el contenido por ID
GET  http://localhost:3000/contenidos/1

### Filtrar por titilo
GET  http://localhost:3000/contenidos/filter/titulo?titulo=Alien

### Filtrar contenido por categoria
GET http://localhost:3000/contenidos/filter/categoria?categoria=peli

### Filtrar contenido por genero
GET http://localhost:3000/contenidos/filter/genero?genero=Sci

### Crea un nuevo contenido
POST http://localhost:3000/contenidos
Content-Type: application/json

{
  "poster": "./posters/99.jpg",
  "titulo": "Gladiator 2",
  "categoria": "Película",
  "generos": ["Acción", "drama", "péplum", "aventuras", "cine histórico", "cine épico"],
  "resumen": "Después de ser salvado por Máximo Décimo Meridio en Gladiator, Lucio Vero —en Latín Lucius— el sobrino del emperador Cómodo e hijo de Lucila, ahora es una persona que debe tomar decisiones importantes.",
  //"temporadas": "N/A",
  "reparto": ["Pedro Pascal", "Denzel Washington"],
  "trailer": "https://www.youtube.com/watch?v=Ts0N8swyWFI",
  "duracion": 180
}
