### Home API
GET  http://localhost:3000/

### Muestra todo el contenido
GET  http://localhost:3000/contenidos

### Muestra el contenido por ID
GET  http://localhost:3000/contenidos/101

### Filtrar por titilo
GET  http://localhost:3000/contenidos/filter/titulo?titulo=Alien

### Filtrar contenido por categoria
GET http://localhost:3000/contenidos/filter/categoria?categoria=peli

### Filtrar contenido por genero
GET http://localhost:3000/contenidos/filter/genero?genero=Sci

### Crea un nuevo contenido
POST http://localhost:3000/contenidos
Content-Type: application/json

{
  "poster": "./posters/99.jpg",
  "titulo": "Gladiator 2",
  "categoria": "Película",
  "generos": ["Acción", "drama", "péplum", "aventuras", "cine histórico", "cine épico"],
  "resumen": "Después de ser salvado por Máximo Décimo Meridio en Gladiator, Lucio Vero —en Latín Lucius— el sobrino del emperador Cómodo e hijo de Lucila, ahora es una persona que debe tomar decisiones importantes.",
  "temporadas": "N/A",
  "reparto": ["Pedro Pascal", "Denzel Washington"],
  "trailer": "https://www.youtube.com/watch?v=Ts0N8swyWFI",
  "duracion": 180
}

### Actualiza el contenido por ID
PUT http://localhost:3000/contenidos/101
Content-Type: application/json

{
  "poster": "./posters/101.jpg",
  "titulo": "The Rings of Power",
  "categoria": "Serie",
  "generos": ["Acción", "Fantasía", "Aventura"],
  "resumen": "Ambientada miles de años antes de los eventos de El Hobbit y El Señor de los Anillos, la serie se basa en la historia de la Tierra Media del autor J. R. R. Tolkien. Comienza durante una época de relativa paz y cubre todos los eventos principales de la Segunda Edad de la Tierra Media: la forja de los Anillos de Poder, el surgimiento del Señor Oscuro Sauron, la historia del reino insular de Númenor y la última alianza entre Elfos y Hombres. Estos eventos tienen lugar durante miles de años en las historias originales de Tolkien, pero se condensan para la serie.",
  "temporadas": "2",
  "reparto": ["Morfydd Clark", "Robert Aramayo"],
  "trailer": "https://www.youtube.com/watch?v=TCwmXY_f-e0",
  "duracion": 0
}
